package com.cdfortis.datainterface.soap;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class NetworkCredential implements KvmSerializable {
    
    public String userName;
    public String password;
    public SecureString securePassword;
    public String domain;
    
    public NetworkCredential(){}
    
    public NetworkCredential(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("UserName"))
        {
            Object obj = soapObject.getProperty("UserName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                userName = j.toString();
            }else if (obj!= null && obj instanceof String){
                userName = (String) obj;
            }
        }
        if (soapObject.hasProperty("Password"))
        {
            Object obj = soapObject.getProperty("Password");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                password = j.toString();
            }else if (obj!= null && obj instanceof String){
                password = (String) obj;
            }
        }
        if (soapObject.hasProperty("SecurePassword"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("SecurePassword");
            securePassword =  new SecureString (j);
            
        }
        if (soapObject.hasProperty("Domain"))
        {
            Object obj = soapObject.getProperty("Domain");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                domain = j.toString();
            }else if (obj!= null && obj instanceof String){
                domain = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return userName;
            case 1:
                return password;
            case 2:
                return securePassword;
            case 3:
                return domain;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "UserName";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Password";
                break;
            case 2:
                info.type = SecureString.class;
                info.name = "SecurePassword";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Domain";
                break;
        }
    }
    
//    @Override
//    public String getInnerText() {
//        return null;
//    }
    
    
//    @Override
//    public void setInnerText(String s) {
//    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
