package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Appointment extends SoapObjectData {

    @DataField
    public String account;
    @DataField
    public String appt_id;

    public Appointment(SoapObject soapObject) {
        super(soapObject);
    }

}
