package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class CreditCard implements KvmSerializable {
    
    public String cc_idx;
    public String card_no;
    public String card_type;
    public String holdername;
    public String card_exp_date;
    
    public CreditCard(){}
    
    public CreditCard(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("cc_idx"))
        {
            Object obj = soapObject.getProperty("cc_idx");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cc_idx = j.toString();
            }else if (obj!= null && obj instanceof String){
                cc_idx = (String) obj;
            }
        }
        if (soapObject.hasProperty("card_no"))
        {
            Object obj = soapObject.getProperty("card_no");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                card_no = j.toString();
            }else if (obj!= null && obj instanceof String){
                card_no = (String) obj;
            }
        }
        if (soapObject.hasProperty("card_type"))
        {
            Object obj = soapObject.getProperty("card_type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                card_type = j.toString();
            }else if (obj!= null && obj instanceof String){
                card_type = (String) obj;
            }
        }
        if (soapObject.hasProperty("name_on_card"))
        {
            Object obj = soapObject.getProperty("name_on_card");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                holdername = j.toString();
            }else if (obj!= null && obj instanceof String){
                holdername = (String) obj;
            }
        }
        if (soapObject.hasProperty("card_exp_date"))
        {
            Object obj = soapObject.getProperty("card_exp_date");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                card_exp_date = j.toString();
            }else if (obj!= null && obj instanceof String){
                card_exp_date = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return cc_idx;
            case 1:
                return card_no;
            case 2:
                return card_type;
            case 3:
                return holdername;
            case 4:
                return card_exp_date;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 5;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "cc_idx";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "card_no";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "card_type";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "holdername";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "card_exp_date";
                break;
        }
    }
    
//    @Override
//    public String getInnerText() {
//        return null;
//    }
    
    
//    @Override
//    public void setInnerText(String s) {
//    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
