package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class FamilyInfo implements KvmSerializable {

    public String first_name;
    public String last_name;
    public String email;
    public String mi;
    public String sex;
    public String dOB;
    public String addr1;
    public String addr2;
    public String city;
    public String state;
    public String zip;
    public String phone_number;
    public String relationshipToPatient;
    public String onlineStatus;
    public String account;
    public String user_id;

    public FamilyInfo(){}

    public FamilyInfo(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("first_name"))
        {
            Object obj = soapObject.getProperty("first_name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                first_name = j.toString();
            }else if (obj!= null && obj instanceof String){
                first_name = (String) obj;
            }
        }
        if (soapObject.hasProperty("last_name"))
        {
            Object obj = soapObject.getProperty("last_name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                last_name = j.toString();
            }else if (obj!= null && obj instanceof String){
                last_name = (String) obj;
            }
        }
        if (soapObject.hasProperty("email"))
        {
            Object obj = soapObject.getProperty("email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                email = j.toString();
            }else if (obj!= null && obj instanceof String){
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("mi"))
        {
            Object obj = soapObject.getProperty("mi");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mi = j.toString();
            }else if (obj!= null && obj instanceof String){
                mi = (String) obj;
            }
        }
        if (soapObject.hasProperty("sex"))
        {
            Object obj = soapObject.getProperty("sex");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                sex = j.toString();
            }else if (obj!= null && obj instanceof String){
                sex = (String) obj;
            }
        }
        if (soapObject.hasProperty("DOB"))
        {
            Object obj = soapObject.getProperty("DOB");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                dOB = j.toString();
            }else if (obj!= null && obj instanceof String){
                dOB = (String) obj;
            }
        }
        if (soapObject.hasProperty("addr1"))
        {
            Object obj = soapObject.getProperty("addr1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                addr1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                addr1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("addr2"))
        {
            Object obj = soapObject.getProperty("addr2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                addr2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                addr2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("city"))
        {
            Object obj = soapObject.getProperty("city");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                city = j.toString();
            }else if (obj!= null && obj instanceof String){
                city = (String) obj;
            }
        }
        if (soapObject.hasProperty("state"))
        {
            Object obj = soapObject.getProperty("state");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                state = j.toString();
            }else if (obj!= null && obj instanceof String){
                state = (String) obj;
            }
        }
        if (soapObject.hasProperty("zip"))
        {
            Object obj = soapObject.getProperty("zip");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                zip = j.toString();
            }else if (obj!= null && obj instanceof String){
                zip = (String) obj;
            }
        }
        if (soapObject.hasProperty("phone_number"))
        {
            Object obj = soapObject.getProperty("phone_number");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                phone_number = j.toString();
            }else if (obj!= null && obj instanceof String){
                phone_number = (String) obj;
            }
        }

        //default state
        if (soapObject.hasProperty("relationshipToPatient"))
        {
            Object obj = soapObject.getProperty("relationshipToPatient");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                relationshipToPatient = j.toString();
            }else if (obj!= null && obj instanceof String){
                relationshipToPatient = (String) obj;
            }
        }
        // service code
        if (soapObject.hasProperty("onlineStatus"))
        {
            Object obj = soapObject.getProperty("onlineStatus");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                onlineStatus = j.toString();
            }else if (obj!= null && obj instanceof String){
                onlineStatus = (String) obj;
            }
        }
        // service code
        if (soapObject.hasProperty("account"))
        {
            Object obj = soapObject.getProperty("account");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                account = j.toString();
            }else if (obj!= null && obj instanceof String){
                account = (String) obj;
            }
        }
        if (soapObject.hasProperty("user_id"))
        {
            Object obj = soapObject.getProperty("user_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                user_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                user_id = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return first_name == null ? "" : first_name;
            case 1:
                return last_name == null ? "" :last_name;
            case 2:
                return email == null ? "" : email;
            case 3:
                return mi == null ? "" : mi ;
            case 4:
                return sex == null ? "":sex;
            case 5:
                return dOB == null ? "" : dOB;
            case 6:
                return addr1 == null? "": addr1;
            case 7:
                return addr2 == null ? "" : addr2;
            case 8:
                return city == null ? "" : city;
            case 9:
                return state == null ? "" : state;
            case 10:
                return zip == null ? "" : zip;
            case 11:
                return phone_number == null ? "" : phone_number;
            case 12:
                return relationshipToPatient == null ? "" : relationshipToPatient;
            case 13:
                return onlineStatus == null ? "" : onlineStatus;
            case 14:
                return account == null ? "" : account;
            case 15:  return user_id == null ? "" : user_id;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 15;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "first_name";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "last_name";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "email";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mi";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "sex";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "DOB";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "addr1";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "addr2";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "city";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "state";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "zip";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "phone_number";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "relationshipToPatient";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "onlineStatus";
                break;
            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "account";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "user_id";
                break;
        }
    }
    
//    @Override
//    public String getInnerText() {
//        return null;
//    }
    
    
//    @Override
//    public void setInnerText(String s) {
//    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
