package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class FavoritePharmacy implements KvmSerializable {

    public String pharmacy_name;
    public String longitude;
    public String latitude;
    public String address1;
    public String address2;
    public String city;
    public String state;
    public String country;
    public String zip_code;
    public String type;

    public FavoritePharmacy(){}

    public FavoritePharmacy(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("pharmacy_name"))
        {
            Object obj = soapObject.getProperty("pharmacy_name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pharmacy_name = j.toString();
            }else if (obj!= null && obj instanceof String){
                pharmacy_name = (String) obj;
            }
        }
        if (soapObject.hasProperty("longitude"))
        {
            Object obj = soapObject.getProperty("longitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                longitude = j.toString();
            }else if (obj!= null && obj instanceof String){
                longitude = (String) obj;
            }
        }
        if (soapObject.hasProperty("latitude"))
        {
            Object obj = soapObject.getProperty("latitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                latitude = j.toString();
            }else if (obj!= null && obj instanceof String){
                latitude = (String) obj;
            }
        }
        if (soapObject.hasProperty("address1"))
        {
            Object obj = soapObject.getProperty("address1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                address1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                address1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("address2"))
        {
            Object obj = soapObject.getProperty("address2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                address2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                address2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("city"))
        {
            Object obj = soapObject.getProperty("city");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                city = j.toString();
            }else if (obj!= null && obj instanceof String){
                city = (String) obj;
            }
        }
        if (soapObject.hasProperty("state"))
        {
            Object obj = soapObject.getProperty("state");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                state = j.toString();
            }else if (obj!= null && obj instanceof String){
                state = (String) obj;
            }
        }
        if (soapObject.hasProperty("country"))
        {
            Object obj = soapObject.getProperty("country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                country = j.toString();
            }else if (obj!= null && obj instanceof String){
                country = (String) obj;
            }
        }
        if (soapObject.hasProperty("zip_code"))
        {
            Object obj = soapObject.getProperty("zip_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                zip_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                zip_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("type"))
        {
            Object obj = soapObject.getProperty("type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                type = j.toString();
            }else if (obj!= null && obj instanceof String){
                type = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return pharmacy_name;
            case 1:
                return longitude;
            case 2:
                return latitude;
            case 3:
                return address1;
            case 4:
                return address2;
            case 5:
                return city;
            case 6:
                return state;
            case 7:
                return country;
            case 8:
                return zip_code;
            case 9:
                return type;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 10;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "pharmacy_name";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "longitude";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "latitude";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "address1";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "address2";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "city";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "state";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "country";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "zip_code";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "type";
                break;
        }
    }
    
//    @Override
//    public String getInnerText() {
//        return null;
//    }
    
    
//    @Override
//    public void setInnerText(String s) {
//    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
