package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class Insurance extends SoapObjectData {

    @DataField
    public String company_code;
    @DataField
    public String company_name;
    @DataField
    public String insurance_id;
    @DataField
    public String pat_insurance_sequence;
    @DataField
    public String pat_relation_to_insured;
    @DataField
    public String insured_first_name;
    @DataField
    public String insured_last_name;
    @DataField
    public String insured_dob;
    @DataField
    public String copay_amount;

    public Insurance() {
    }

    public Insurance(SoapObject soapObject) {
        super(soapObject);
    }


}
