package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class InsuranceCompany implements KvmSerializable {

    public String company_code;
    public String company_name;
    public String address1;
    public String address2;
    public String city;
    public String state;
    public String country;
    public String zip_code;

    public InsuranceCompany(){}

    public InsuranceCompany(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("company_code"))
        {
            Object obj = soapObject.getProperty("company_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                company_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                company_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("company_name"))
        {
            Object obj = soapObject.getProperty("company_name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                company_name = j.toString();
            }else if (obj!= null && obj instanceof String){
                company_name = (String) obj;
            }
        }
        if (soapObject.hasProperty("address1"))
        {
            Object obj = soapObject.getProperty("address1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                address1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                address1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("address2"))
        {
            Object obj = soapObject.getProperty("address2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                address2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                address2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("city"))
        {
            Object obj = soapObject.getProperty("city");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                city = j.toString();
            }else if (obj!= null && obj instanceof String){
                city = (String) obj;
            }
        }
        if (soapObject.hasProperty("state"))
        {
            Object obj = soapObject.getProperty("state");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                state = j.toString();
            }else if (obj!= null && obj instanceof String){
                state = (String) obj;
            }
        }
        if (soapObject.hasProperty("country"))
        {
            Object obj = soapObject.getProperty("country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                country = j.toString();
            }else if (obj!= null && obj instanceof String){
                country = (String) obj;
            }
        }
        if (soapObject.hasProperty("zip_code"))
        {
            Object obj = soapObject.getProperty("zip_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                zip_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                zip_code = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return company_code;
            case 1:
                return company_name;
            case 2:
                return address1;
            case 3:
                return address2;
            case 4:
                return city;
            case 5:
                return state;
            case 6:
                return country;
            case 7:
                return zip_code;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 8;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "company_code";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "company_name";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "address1";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "address2";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "city";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "state";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "country";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "zip_code";
                break;
        }
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
