package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//


import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.SoapObject;

public class IoT_Device extends SoapObjectData implements Comparable<IoT_Device> {

    /*These fields cannot be changed to private*/
    @DataField
    public String device_type;
    @DataField
    public String device_macAddress;
    @DataField
    public String device_model;

    public String cybermed_code;



    public IoT_Device(SoapObject soapObject) {
        super(soapObject);
    }

    public IoT_Device(String device_type, String device_macAddress){
        this.device_type = device_type;
        this.device_macAddress = device_macAddress;
    }

    @Override
    public boolean equals(Object obj) {
        if(obj instanceof  IoT_Device){
            return device_type.equals(((IoT_Device) obj).device_type)
                    && device_macAddress.equals(((IoT_Device) obj).device_macAddress);
        }else{
            return false;
        }
    }

    @Override
    public int hashCode() {
        return device_type.hashCode() + device_macAddress.hashCode();
    }

    public String getCybermed_code() {
        return cybermed_code;
    }

    public void setCybermed_code(String cybermed_code) {
        this.cybermed_code = cybermed_code;
    }

    public String getDevice_type() {
        return device_type;
    }

    public void setDevice_type(String device_type) {
        this.device_type = device_type;
    }

    public String getDevice_macAddress() {
        return device_macAddress;
    }

    public void setDevice_macAddress(String device_macAddress) {
        this.device_macAddress = device_macAddress;
    }

    @Override
    public int compareTo(IoT_Device o) {
        return device_type.compareTo(o.device_type);
    }
}


