package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//


import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.SoapObject;

import java.util.Vector;

public class LabReportRecord extends SoapObjectData {

    /*These fields cannot be changed to private*/
    @DataField
    public String Lab_TestName;
    public Vector<LabResult> labResultVector;

    public LabReportRecord(SoapObject soapObject) {
        super(soapObject);
        labResultVector = new SoapObjectVector<>(LabResult.class, (SoapObject) soapObject.getProperty(1));
    }

}


