package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//


import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.SoapObject;

public class Monitor_HR extends SoapObjectData {

    /*These fields cannot be changed to private*/
    @DataField
    public String HR;
    @DataField
    public String HR_timestamp;


    public Monitor_HR(SoapObject soapObject) {
        super(soapObject);
    }

}


