package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class MyVitals implements KvmSerializable, Serializable {

    public String chief_complaint;
    public String pulse;
    public String temperature;
    public String bph;
    public String bpl;
    public String height;
    public String weight;
    public String BMI;
    public String MedHx;
    public String SocialHx;
    public String allergies;
    public String smoke_status_code;
    public String smoke_status_desc;
    public String spo2;
    public String timestamp;
    public String spo2_timestamp;
    public String pulse_timestamp;
    public String temperature_timestamp;
    public String BP_timestamp;
    public String height_timestamp;
    public String weight_timestamp;

    public MyVitals(){}

    public MyVitals(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("chief_complaint"))
        {
            Object obj = soapObject.getProperty("chief_complaint");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                chief_complaint = j.toString();
            }else if (obj!= null && obj instanceof String){
                chief_complaint = (String) obj;
            }
        }
        if (soapObject.hasProperty("pulse"))
        {
            Object obj = soapObject.getProperty("pulse");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pulse = j.toString();
            }else if (obj!= null && obj instanceof String){
                pulse = (String) obj;
            }
        }
        if (soapObject.hasProperty("temperature"))
        {
            Object obj = soapObject.getProperty("temperature");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                temperature = j.toString();
            }else if (obj!= null && obj instanceof String){
                temperature = (String) obj;
            }
        }
        if (soapObject.hasProperty("bph"))
        {
            Object obj = soapObject.getProperty("bph");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                bph = j.toString();
            }else if (obj!= null && obj instanceof String){
                bph = (String) obj;
            }
        }
        if (soapObject.hasProperty("bpl"))
        {
            Object obj = soapObject.getProperty("bpl");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                bpl = j.toString();
            }else if (obj!= null && obj instanceof String){
                bpl = (String) obj;
            }
        }
        if (soapObject.hasProperty("height"))
        {
            Object obj = soapObject.getProperty("height");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                height = j.toString();
            }else if (obj!= null && obj instanceof String){
                height = (String) obj;
            }
        }
        if (soapObject.hasProperty("weight"))
        {
            Object obj = soapObject.getProperty("weight");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                weight = j.toString();
            }else if (obj!= null && obj instanceof String){
                weight = (String) obj;
            }
        }
        if (soapObject.hasProperty("BMI"))
        {
            Object obj = soapObject.getProperty("BMI");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                BMI = j.toString();
            }else if (obj!= null && obj instanceof String){
                BMI = (String) obj;
            }
        }
        if (soapObject.hasProperty("MedHx"))
        {
            Object obj = soapObject.getProperty("MedHx");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                MedHx = j.toString();
            }else if (obj!= null && obj instanceof String){
                MedHx = (String) obj;
            }
        }
        if (soapObject.hasProperty("SocialHx"))
        {
            Object obj = soapObject.getProperty("SocialHx");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                SocialHx = j.toString();
            }else if (obj!= null && obj instanceof String){
                SocialHx = (String) obj;
            }
        }
        if (soapObject.hasProperty("allergies"))
        {
            Object obj = soapObject.getProperty("allergies");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                allergies = j.toString();
            }else if (obj!= null && obj instanceof String){
                allergies = (String) obj;
            }
        }
        if (soapObject.hasProperty("smoke_status_code"))
        {
            Object obj = soapObject.getProperty("smoke_status_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                smoke_status_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                smoke_status_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("smoke_status_desc"))
        {
            Object obj = soapObject.getProperty("smoke_status_desc");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                smoke_status_desc = j.toString();
            }else if (obj!= null && obj instanceof String){
                smoke_status_desc = (String) obj;
            }
        }
        if (soapObject.hasProperty("spo2"))
        {
            Object obj = soapObject.getProperty("spo2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                spo2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                spo2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("timestamp"))
        {
            Object obj = soapObject.getProperty("timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("spo2_timestamp"))
        {
            Object obj = soapObject.getProperty("spo2_timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                spo2_timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                spo2_timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("pulse_timestamp"))
        {
            Object obj = soapObject.getProperty("pulse_timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                pulse_timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                pulse_timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("temperature_timestamp"))
        {
            Object obj = soapObject.getProperty("temperature_timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                temperature_timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                temperature_timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("BP_timestamp"))
        {
            Object obj = soapObject.getProperty("BP_timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                BP_timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                BP_timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("height_timestamp"))
        {
            Object obj = soapObject.getProperty("height_timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                height_timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                height_timestamp = (String) obj;
            }
        }
        if (soapObject.hasProperty("weight_timestamp"))
        {
            Object obj = soapObject.getProperty("weight_timestamp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                weight_timestamp = j.toString();
            }else if (obj!= null && obj instanceof String){
                weight_timestamp = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return chief_complaint == null ? "" : chief_complaint;
            case 1:
                return pulse == null ? "" : pulse;
            case 2:
                return temperature == null ? "" : temperature;
            case 3:
                return bph == null ? "" : bph;
            case 4:
                return bpl == null ? "" : bpl;
            case 5:
                return height == null ? "" : height;
            case 6:
                return weight == null ? "" : weight;
            case 7:
                return BMI == null ? "" : BMI;
            case 8:
                return MedHx == null ? "" : MedHx;
            case 9:
                return SocialHx == null ? "" : SocialHx;
            case 10:
                return allergies == null ? "" : allergies;
            case 11:
                return smoke_status_code == null ? "" : smoke_status_code;
            case 12:
                return smoke_status_desc == null ? "" : smoke_status_desc;
            case 13:
                return spo2 == null ? "" : spo2;
            case 14:
                return timestamp == null ? "" : timestamp;
            case 15:
                return spo2_timestamp == null ? "" : spo2_timestamp;
            case 16:
                return pulse_timestamp == null ? "" : pulse_timestamp;
            case 17:
                return temperature_timestamp == null ? "" : temperature_timestamp;
            case 18:
                return BP_timestamp == null ? "" : BP_timestamp;
            case 19:
                return height_timestamp == null ? "" : height_timestamp;
            case 20:
                return weight_timestamp == null ? "" : weight_timestamp;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 21;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "chief_complaint";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "pulse";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "temperature";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "bph";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "bpl";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "height";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "weight";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "BMI";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MedHx";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "SocialHx";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "allergies";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "smoke_status_code";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "smoke_status_desc";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "spo2";
                break;
            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "timestamp";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "spo2_timestamp";
                break;
            case 16:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "pulse_timestamp";
                break;
            case 17:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "temperature_timestamp";
                break;
            case 18:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "BP_timestamp";
                break;
            case 19:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "height_timestamp";
                break;
            case 20:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "weight_timestamp";
                break;
        }
    }
    
//    @Override
//    public String getInnerText() {
//        return null;
//    }
    
    
//    @Override
//    public void setInnerText(String s) {
//    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
