package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import android.os.Parcel;
import android.os.Parcelable;

import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class PatientAppointment extends SoapObjectData implements Parcelable {

    @DataField
    public String appt_id;
    @DataField
    public String appt_date;
    @DataField
    public String account;
    @DataField
    public String patient_name;
    @DataField
    public String appt_status;
    @DataField
    public String chief_complaint;
    @DataField
    public String room_number;
    @DataField
    public String reachback_phone_number;
    @DataField
    public String provider_code;
    @DataField
    public String start_time;
    @DataField
    public String end_time;
    @DataField
    public String org_code;
    @DataField
    public String provider_first_name;
    @DataField
    public String provider_last_name;
    @DataField
    public String provider_specialties;
    @DataField
    public String provider_languages;
    @DataField
    public String talk_time;
    @DataField
    public String amount_paid;

    public PatientAppointment(SoapObject soapObject) {
        super(soapObject);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.appt_id);
        dest.writeString(this.appt_date);
        dest.writeString(this.account);
        dest.writeString(this.patient_name);
        dest.writeString(this.appt_status);
        dest.writeString(this.chief_complaint);
        dest.writeString(this.room_number);
        dest.writeString(this.reachback_phone_number);
        dest.writeString(this.provider_code);
        dest.writeString(this.start_time);
        dest.writeString(this.end_time);
        dest.writeString(this.org_code);
        dest.writeString(this.provider_first_name);
        dest.writeString(this.provider_last_name);
        dest.writeString(this.provider_specialties);
        dest.writeString(this.provider_languages);
        dest.writeString(this.talk_time);
        dest.writeString(this.amount_paid);

    }

    public void readFromParcel(Parcel source) {
        this.appt_id = source.readString();
        this.appt_date = source.readString();
        this.account = source.readString();
        this.patient_name = source.readString();
        this.appt_status = source.readString();
        this.chief_complaint = source.readString();
        this.room_number = source.readString();
        this.reachback_phone_number = source.readString();
        this.provider_code = source.readString();
        this.start_time = source.readString();
        this.end_time = source.readString();
        this.org_code = source.readString();
        this.provider_first_name = source.readString();
        this.provider_last_name = source.readString();
        this.provider_specialties = source.readString();
        this.provider_languages = source.readString();
        this.talk_time = source.readString();
        this.amount_paid = source.readString();

    }

    protected PatientAppointment(Parcel in) {
        this.appt_id = in.readString();
        this.appt_date = in.readString();
        this.account = in.readString();
        this.patient_name = in.readString();
        this.appt_status = in.readString();
        this.chief_complaint = in.readString();
        this.room_number = in.readString();
        this.reachback_phone_number = in.readString();
        this.provider_code = in.readString();
        this.start_time = in.readString();
        this.end_time = in.readString();
        this.org_code = in.readString();
        this.provider_first_name = in.readString();
        this.provider_last_name = in.readString();
        this.provider_specialties = in.readString();
        this.provider_languages = in.readString();
        this.talk_time = in.readString();
        this.amount_paid = in.readString();

    }

    public static final Parcelable.Creator<PatientAppointment> CREATOR = new Parcelable.Creator<PatientAppointment>() {
        @Override
        public PatientAppointment createFromParcel(Parcel source) {
            return new PatientAppointment(source);
        }

        @Override
        public PatientAppointment[] newArray(int size) {
            return new PatientAppointment[size];
        }
    };
}


