package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//


import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.SoapObject;

public class Patient_Info extends SoapObjectData {

    /*These fields cannot be changed to private*/
    @DataField
    public String first_name;
    @DataField
    public String last_name;
    @DataField
    public String email;
    @DataField
    public String mi;
    @DataField
    public String sex;
    @DataField
    public String DOB;
    @DataField
    public String addr1;
    @DataField
    public String addr2;
    @DataField
    public String city;
    @DataField
    public String state;
    @DataField
    public String zip;
    @DataField
    public String phone_number;
    @DataField
    public String service_code;
    @DataField
    public String default_state;
    @DataField
    public String mobile_mode;


    public Patient_Info(SoapObject soapObject) {
        super(soapObject);
    }

}


