package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.util.Hashtable;

public class Paypal implements KvmSerializable {

    public String account;
    public String active_status;

    public Paypal(){}

    public Paypal(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("account"))
        {
            Object obj = soapObject.getProperty("account");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                account = j.toString();
            }else if (obj!= null && obj instanceof String){
                account = (String) obj;
            }
        }
        if (soapObject.hasProperty("active_status"))
        {
            Object obj = soapObject.getProperty("active_status");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                active_status = j.toString();
            }else if (obj!= null && obj instanceof String){
                active_status = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return account;
            case 1:
                return active_status;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 2;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "account";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "active_status";
                break;
        }
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
