package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class ProviderAvaliability extends SoapObjectData {

    @DataField
    public String appt_id;
    @DataField
    public String appt_date;
    @DataField
    public String account;
    @DataField
    public String patient_name;
    @DataField
    public String appt_status;
    @DataField
    public String chief_complaint;
    @DataField
    public String room_number;
    @DataField
    public String reachback_phone_number;
    @DataField
    public String provider_code;
    @DataField
    public String start_time;
    @DataField
    public String end_time;

    public ProviderAvaliability(SoapObject soapObject) {
        super(soapObject);
    }
}


