package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.util.Hashtable;

public class ProviderReviews implements KvmSerializable, Serializable {

    public String rating_score;
    public String comment;
    public String review_date;

    public ProviderReviews(){}

    public ProviderReviews(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("rating_score"))
        {
            Object obj = soapObject.getProperty("rating_score");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                rating_score = j.toString();
            }else if (obj!= null && obj instanceof String){
                rating_score = (String) obj;
            }
        }
        if (soapObject.hasProperty("comment"))
        {
            Object obj = soapObject.getProperty("comment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                comment = j.toString();
            }else if (obj!= null && obj instanceof String){
                comment = (String) obj;
            }
        }
        if (soapObject.hasProperty("review_date"))
        {
            Object obj = soapObject.getProperty("review_date");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                review_date = j.toString();
            }else if (obj!= null && obj instanceof String){
                review_date = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return rating_score == null ? "" : rating_score;
            case 1:
                return comment == null ? "" : comment;
            case 2:
                return review_date == null ? "" : review_date;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "rating_score";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "comment";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "review_date";
                break;
        }
    }
    
//    @Override
//    public String getInnerText() {
//        return null;
//    }
    
    
//    @Override
//    public void setInnerText(String s) {
//    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
