package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.SoapObject;

public class ReferralRecord extends SoapObjectData {

    /*These fields cannot be changed to private*/
    @DataField
    public String Referrals_Date;
    @DataField
    public String Referrals_ReferredTo;
    @DataField
    public String Referrals_Status;
    @DataField
    public String Referrals_From;
    @DataField
    public String Referrals_To;
    @DataField
    public String Referrals_FromPhone;
    @DataField
    public String Referrals_ToPhone;
    @DataField
    public String Referrals_OtherInfo;

    public ReferralRecord(SoapObject soapObject) {
        super(soapObject);
    }
}


