package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import android.util.Log;

import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Hashtable;
import java.util.List;

public class SoapObjectData implements KvmSerializable, Serializable {

    private String[] properties;

    public SoapObjectData() {
    }

    public SoapObjectData(SoapObject soapObject) {
        if (soapObject == null)
            return;

        /*Declare and initialized Fields*/
        Field[] fields = getClass().getDeclaredFields();
        List<Field> dataFields = new ArrayList<>();

        /*pick out the DataField*/
        for(Field field : fields){
            if(field.getAnnotation(DataField.class) != null){
                dataFields.add(field);
            }
        }

        String[] properties = new String[dataFields.size()];

        for (int index = 0; index < properties.length; index++) {
            properties[index] = dataFields.get(index).getName();
        }

        this.properties = properties;

        for (String property : properties) {
            if (soapObject.hasProperty(property)) {
                Object obj = soapObject.getProperty(property);

                try {
                    Field field = getClass().getDeclaredField(property);

                    if (obj instanceof SoapPrimitive) {
                        SoapPrimitive j = (SoapPrimitive) obj;
                        field.set(this, j.toString());
                    } else if (obj instanceof String) {
                        field.set(this, obj);
                    }
                } catch (NoSuchFieldException e) {
                    e.printStackTrace();
                } catch (IllegalAccessException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        try {
            Field field = getClass().getDeclaredField(properties[arg0]);
            return field.get(this);
        } catch (ArrayIndexOutOfBoundsException e) {
            return null;
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return properties.length;
    }

    @Override
    public void setProperty(int i, Object o) {

    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {

        try {
            Field field = getClass().getDeclaredField(properties[index]);
            info.type = PropertyInfo.STRING_CLASS;
            info.name = (String) field.get(this);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (ClassCastException e) {
            e.printStackTrace();
        }
    }

    public String[] getProperties() {
        return properties;
    }
}


