package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/5/2017 1:17:36 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.ParameterizedType;
import java.lang.reflect.TypeVariable;
import java.util.Hashtable;
import java.util.Vector;

public class SoapObjectVector<T> extends Vector<T> implements KvmSerializable {

    public SoapObjectVector() {
    }

    /*Daniel on 2/22/2019 does not have the capability to complete this method. Please Help*/
//    public SoapObjectVector(SoapObject soapObject) {
//        this(null, soapObject);
//    }
//            if(genericClass == null) {
//        ParameterizedType genericSuperclass = (ParameterizedType) getClass()
//                .getGenericSuperclass();
//        genericClass = (Class<T>) ((TypeVariable)genericSuperclass.getActualTypeArguments()[0]).getGenericDeclaration();
//    }
    /**/

    public SoapObjectVector(Class<T> genericClass, SoapObject soapObject) {
        if (soapObject == null)
            return;

        int size = soapObject.getPropertyCount();

        for (int index = 0; index < size; index++) {
            Object obj = soapObject.getProperty(index);
            if (obj instanceof SoapObject) {
                try {
                    Constructor<T> constructor = genericClass.getConstructor(SoapObject.class);
                    T visitRecord = constructor.newInstance((SoapObject) obj);
                    add(visitRecord);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        return this.get(arg0);
    }

    @Override
    public int getPropertyCount() {
        return this.size();
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        info.name = "VisitRecord";
        info.type = VisitRecord.class;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
