package com.cdfortis.datainterface.soap.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 6/6/2017 2:51:30 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import com.cdfortis.datainterface.annotation.DataField;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

import java.io.Serializable;
import java.lang.reflect.Field;
import java.util.Hashtable;

public class VisitRecord extends SoapObjectData {

    /*These fields cannot be changed to private*/
    @DataField
    public String org_code;
    @DataField
    public String org_name;
    @DataField
    public String account;

    @Override
    public boolean equals(Object obj) {
        if (!(obj instanceof VisitRecord))
            return false;

        VisitRecord visitRecord = (VisitRecord) obj;

        return org_code.equalsIgnoreCase(visitRecord.org_code);
    }

    @Override
    public int hashCode() {
        return org_code.hashCode();
    }

    @DataField
    public String visit_datetime;

    public VisitRecord(SoapObject soapObject) {
        super(soapObject);
    }

    public VisitRecord(String org_code, String account) {
        this.org_code = org_code;
        this.account = account;
        org_name = "";
    }
}


