//apply plugin: 'com.android.library'
plugins {
    id 'maven-publish'
    id 'com.android.library'
}

android {
    compileSdk 36


    defaultConfig {

        minSdkVersion 18
        //noinspection EditedTargetSdkVersion
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    /*task makejar(type: Jar) {
        from file('build/intermediates/javac/debug/compileDebugJavaWithJavac/classes')
        archiveName = '1963sdk' + defaultConfig.versionName + '.jar'
        destinationDir = file('build/libs')
        include "com/jstyle/blesdk1963/**"

    }*/
    task makejar(type: Jar) {
        from file('build/intermediates/javac/debug/compileDebugJavaWithJavac/classes')
        archiveFileName.set("1963sdk${defaultConfig.versionName}.jar")
        destinationDirectory.set(file('build/libs'))
        include "com/jstyle/blesdk1963/**"
    }
    namespace 'com.jstyle.blesdk1963'
    lint {
        abortOnError false
        targetSdk 36
    }
    testOptions {
        targetSdk 36
    }
    makejar.dependsOn(build)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])


    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
